FROM jenkins/jenkins:2.504.1-lts-jdk17

USER jenkins
# Instale APENAS o metaplugin do Blue Ocean (deixe resolver as deps)
# opção A: versão fixa conhecida compatível
#RUN jenkins-plugin-cli --plugins blueocean:1.27.21 timestamper:1.17 pollscm:1.3.1 build-timestamp:1.0.3
# opção B (alternativa): pegar sempre a mais recente
# RUN jenkins-plugin-cli --plugins blueocean
RUN jenkins-plugin-cli --jenkins-version 2.504.1 \
  --plugins \
    blueocean \
    json-path-api \
    timestamper \
    pollscm \
    build-timestamp

USER root
ENV DEBIAN_FRONTEND=noninteractive
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

RUN apt update && apt install -y python3 python3-pip python3-venv
RUN python3 -m venv /usr/src/app/venv
ENV PATH="/usr/src/app/venv/bin:$PATH"

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt

# Scripts de init
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy  /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy